services:
  - type: web
    name: classroom-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
    plan: free
    envVars:
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_DB_NAME
        value: classroom
